### ISSUE TITLE
Separate trace preprocessing and upload

### ISSUE THREAD

**Issue by salsolatragus** [cqse/teamscale-profiler-dotnet#120]
Currently, we handle trace-file preprocessing (such as conversion to simple line coverage and coverage merging) during the upload process, which leads to complex control flow (some file are uploaded immediately, others are cached and uploaded later).

To enable future extension fo this logic, I would suggest to separate preprocessing from uploading. For example, we could perform preprocessing as the first task, which takes files from the "inbox" (trace dir) and writes upload batches to a staging directory. Then the upload would take these batches from the staging area, upload, and archive them.

For line coverage this would mean conversion, merging, and writing the merged file as one batch. For method coverage this would mean grouping the files as is into a batch (I just learned that we can send multiple files as a "session" to Teamscale, such that they are processed as a single commit, which would avoid bloating the activity log, even if we cannot merge the data into a single file).

**Comment by karottenreibe** [comment]
I'd prefer an approach that does not need a staging directory, because we'd need to write all meta data to that directory as well, which would require making the IUploads serializable and deserializable. Plus we'd need logic to continue if preprocessing is aborted with an exception etc.

IMO all preprocessing should be purely in-memory.

Also please note that the .NET ephemeral trace upload is not part of the usual upload pipeline so I'm not sure it supports uploading several trace files at once. We'll have to verify that first before implementing any batch upload.

**Comment by karottenreibe** [comment]
Migrated as TS-21167
